//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prb.SqliteDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hw_MasterInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hw_MasterInfo()
        {
            this.Hw_DetailInfo = new HashSet<Hw_DetailInfo>();
            this.Hw_IpMacAddress = new HashSet<Hw_IpMacAddress>();
            this.Hw_Sw_Installed = new HashSet<Hw_Sw_Installed>();
            this.Hw_Sw_Running = new HashSet<Hw_Sw_Running>();
            this.Hw_Sw_Services = new HashSet<Hw_Sw_Services>();
        }
    
        public int HwMasterInfoId { get; set; }
        public int SiteId { get; set; }
        public int ScheduleId { get; set; }
        public int HwTypeId { get; set; }
        public string DevType { get; set; }
        public string DevCategory { get; set; }
        public string ComType { get; set; }
        public string HwName { get; set; }
        public string Description { get; set; }
        public string IPAddress { get; set; }
        public string MacAddress { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hw_DetailInfo> Hw_DetailInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hw_IpMacAddress> Hw_IpMacAddress { get; set; }
        public virtual Hw_Type Hw_Type { get; set; }
        public virtual Prb_Schedule Prb_Schedule { get; set; }
        public virtual Prb_Site Prb_Site { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hw_Sw_Installed> Hw_Sw_Installed { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hw_Sw_Running> Hw_Sw_Running { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hw_Sw_Services> Hw_Sw_Services { get; set; }
    }
}
