//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prb.SqliteDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hw_Sw_Services
    {
        public int SwServiceId { get; set; }
        public int HwMasterInfoId { get; set; }
        public string Caption { get; set; }
        public string Name { get; set; }
        public string DisplayName { get; set; }
        public string Description { get; set; }
        public string PathName { get; set; }
        public string ServiceType { get; set; }
        public Nullable<bool> Started { get; set; }
        public string StartMode { get; set; }
        public string StartName { get; set; }
        public string State { get; set; }
        public string Status { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Hw_MasterInfo Hw_MasterInfo { get; set; }
    }
}
