//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prb.SqliteDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prb_Schedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Prb_Schedule()
        {
            this.Hw_MasterInfo = new HashSet<Hw_MasterInfo>();
        }
    
        public int ScheduleId { get; set; }
        public int SiteId { get; set; }
        public Nullable<int> SettingId { get; set; }
        public Nullable<System.DateTime> StartDateTime { get; set; }
        public Nullable<System.DateTime> EndDateTime { get; set; }
        public string Description { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hw_MasterInfo> Hw_MasterInfo { get; set; }
        public virtual Prb_Setting Prb_Setting { get; set; }
        public virtual Prb_Site Prb_Site { get; set; }
    }
}
