//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prb.SqliteDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prb_Setting
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Prb_Setting()
        {
            this.Prb_Schedule = new HashSet<Prb_Schedule>();
            this.Prb_ADConnectionFailure = new HashSet<Prb_ADConnectionFailure>();
        }
    
        public int SettingId { get; set; }
        public int SiteId { get; set; }
        public string DomainType { get; set; }
        public string DomainName { get; set; }
        public string DomainAdminUser { get; set; }
        public string Password { get; set; }
        public Nullable<bool> WindowsAccess { get; set; }
        public Nullable<bool> MacAccess { get; set; }
        public Nullable<bool> LinuxAccess { get; set; }
        public Nullable<bool> PrintersAccess { get; set; }
        public Nullable<bool> RoutersSwitchesAccess { get; set; }
        public Nullable<bool> OthersAccess { get; set; }
        public Nullable<bool> HardwareDetail { get; set; }
        public Nullable<bool> SoftwareDetail { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> IsRead { get; set; }
        public string ProbeRunningDomain { get; set; }
        public string ProbeRunningMachine { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prb_Schedule> Prb_Schedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prb_ADConnectionFailure> Prb_ADConnectionFailure { get; set; }
    }
}
